Refactor purposes page to use purpose ids as values
DEFRA/water-abstraction-system pull request #1025
Opened 2024-05-16 13:26 UTC by robertparkinson

https://eaflood.atlassian.net/browse/WATER-4294

As part of our work to get the requirements for returns set up we need to know which of the purposes the user has selected in the manual journey so that we can then get the information later at the check your answers page.

This PR changes the logic to store the ID rather than the string which describes the purpose. that way we can look it up again.

2024-05-16 16:16 UTC, Cruikshanks requested changes
I had 1 NIT about perhaps using `map()` instead of the `forEach()`.

My key question though is about replacing stubbing with injecting real records in the tests. I'm not sure it is necessary but happy to be proved wrong!

2024-05-16 16:16 UTC, Cruikshanks commented on app/services/return-requirements/submit-purpose.service.js
> +  })
Sorry! Small NIT.

I think this scenario is what `map()` is idiomatically suited for.

```suggestion
  const purposeIds = purposesData.map((purpose) => {
    return purpose.id
  })
```

2024-05-16 16:16 UTC, Cruikshanks commented on test/services/return-requirements/fetch-licence-purposes.service.test.js
> +describe('Return Requirements - Fetch Purposes for a given licence service', () => {
Can't disagree the title is more meaningful. But it breaks our convention of using the module name.

```suggestion
describe('Return Requirements - Fetch Licence Purposes service', () => {
```

2024-05-16 16:16 UTC, Cruikshanks commented on test/services/return-requirements/fetch-licence-purposes.service.test.js
> +const FetchPurposesService = require('../../../app/services/return-requirements/fetch-licence-purposes.service.js')
In VSCode, highlight the word, hit `fn+F2` then type `FetchLicencePurposes` and watch the magic happen!

```suggestion
const FetchLicencePurposesService = require('../../../app/services/return-requirements/fetch-licence-purposes.service.js')
```

2024-05-16 16:16 UTC, Cruikshanks commented on test/services/return-requirements/purpose.service.test.js
Before wading in, is there a reason _not_ to continue stubbing the fetch service? We've switched to injecting real records instead.

We'll have tested `FetchLicencePurposesService` elsewhere, so I don't think we are at risk by not calling it for real within this test. 🤷

2024-05-16 16:16 UTC, Cruikshanks commented on test/services/return-requirements/submit-purpose.service.test.js
Same question about stubbing VS real data applies here.

2024-05-17 08:24 UTC, robertparkinson commented on test/services/return-requirements/purpose.service.test.js
I guss I can revert it now. I changed it because I was doing the additional call to get all the purposeIds and I wanted to make sure it was calling it correctly

2024-05-17 09:16 UTC, Cruikshanks approved these changes
<img src="https://media3.giphy.com/media/esYUbUzG6YAn2LaVxX/giphy.gif"/>

2024-05-17 09:20 UTC, merged