Feature view requirements for returns
DEFRA/water-abstraction-system pull request #1106
Opened 2024-06-14 13:37 UTC by jonathangoulding

2024-06-17 19:45 UTC, Cruikshanks requested changes
Started adding specific comments but realised there was going to be quite a few!

But I think its because the needs for the return requirement setup journey have gotten mixed in with this. Whereas I think we can simplify things when just taking the completed record and presenting it.

This will be quicker and easier to pair on and discuss. So, we'll arrange that offline from here and progress there.

2024-06-18 10:02 UTC, jonathangoulding reviewed
Comments to address based on conversation

2024-06-18 10:02 UTC, jonathangoulding commented on app/services/return-requirements/fetch-requirements-for-returns.service.js
> +function _agreementExceptions (returnRequirement) {
move all these out

2024-06-19 14:01 UTC, closed without merging

2024-06-19 14:01 UTC, jonathangoulding commented
New PR created based on changes required - https://github.com/DEFRA/water-abstraction-system/pull/1118