Persist a new return version and its requirements
DEFRA/water-abstraction-system pull request #1137
Opened 2024-06-24 14:30 UTC by Jozzey

https://eaflood.atlassian.net/browse/WATER-4519

Having completed the return requirements setup journey (returns-required), we need to persist both the return version (start date, reason and notes) along with its return requirements to the database.

When "Approve" is clicked in the `/check` page the data in the session needs to be persisted to:

- water.return_versions
- water.return_requirements
- water.return_requirement_points
- water.return_requirement_purposes

2024-07-07 19:15 UTC, Cruikshanks requested changes
I think we can simplify the tests a little. But before we get into that I thought I should flag this change first.

2024-07-07 19:15 UTC, Cruikshanks commented on app/services/return-requirements/generate-return-version-requirements.service.js
> +}
I'm afraid it's more complicated than this.

`legacy_id` Is an incremental ID by region. In order to figure it out you need to

- Select all return requirements for the same region
- Select the MAX(legacy ID) from the results
- increment the result by 1

Selecting by region can be achieved with a

```suggestion
async function _nextLegacyId (naldRegionId) {
  const { lastLegacyId } = await ReturnRequirementModel.query()
    .max('legacyId as lastLegacyId')
    .where('externalId, 'like', `${naldRegionId}:%`)
    .first()

  if (lastLegacyId) {
    return lastLegacyId + 1
  }

  return 1
}
```

Also, it's been our convention (where we spot it!) _not_ to prefix functions with `_get` or `_set` hence the tweak to the method name.

2024-07-15 14:32 UTC, robertparkinson approved these changes

2024-07-15 14:55 UTC, Beckyrose200 commented on app/services/return-requirements/persist-return-version.service.js
> +const ReturnVersionModel = require('../../models/return-version.model.js')
NIT 
```suggestion
const ReturnRequirementModel = require('../../models/return-requirement.model.js')
const ReturnRequirementPointModel = require('../../models/return-requirement-point.model.js')
const ReturnRequirementPurposeModel = require('../../models/return-requirement-purpose.model.js')
const ReturnVersionModel = require('../../models/return-version.model.js')
```

2024-07-15 14:59 UTC, Beckyrose200 reviewed
<img src="https://media3.giphy.com/media/3o7absbD7PbTFQa0c8/giphy.gif"/>

2024-07-16 09:05 UTC, merged