Import Licence version purpose conditions
DEFRA/water-abstraction-system pull request #1287
Opened 2024-08-27 14:52 UTC by jonathangoulding

https://eaflood.atlassian.net/browse/WATER-4649

We need to replace the import service logic to import a licence from NALD.

We will leave the import service running to add the NALD data in the import tables, but we will slowly replace the import-licence functionality and move this into the system repo.

This change will add the licence versions purpose conditionsto the import logic.

Previous work work add licence version and licence version purpose - https://github.com/DEFRA/water-abstraction-system/pull/1195

2024-08-27 15:00 UTC, jonathangoulding commented on app/services/import/legacy/transform-licence-version-purpose-conditions.service.js
> +      //  validate here -
Add validation

2024-08-27 15:01 UTC, jonathangoulding commented on app/services/import/legacy/process-licence.service.js
> +    await TransformLicenceVersionPurposeConditionsService.go(regionCode, naldLicenceId, transformedLicence)
Add persistence

2024-08-28 14:43 UTC, jonathangoulding commented on app/services/import/legacy/process-licence.service.js
> +    await TransformLicenceVersionPurposeConditionsService.go(regionCode, naldLicenceId, transformedLicence)
Update tests

2024-08-29 08:38 UTC, jonathangoulding commented on app/services/import/persist-licence.service.js
> +  for (const licenceVersionPurposeCondition of licenceVersionPurposeConditions) {
This potentially can be done in a batch but i have followed the previous code pattern.

2024-08-29 16:02 UTC, Cruikshanks requested changes
First pass of corrections and suggested changes.

2024-08-29 16:02 UTC, Cruikshanks commented on app/services/import/persist-licence.service.js
> +async function _persistLicenceVersionPurposesConditions (
```suggestion
async function _persistLicenceVersionPurposeConditions (
```

2024-08-29 16:02 UTC, Cruikshanks commented on app/services/import/persist-licence.service.js
> +async function _persistLicenceVersionPurposeConditions (
```suggestion
async function _persistLicenceVersionPurposeCondition (
```

2024-08-29 16:02 UTC, Cruikshanks commented on app/validators/import/licence-version-purpose-condition.validator.js
> +    )
```suggestion
    })
```

2024-08-29 19:34 UTC, Cruikshanks submitted a review, later dismissed

2024-08-30 09:10 UTC, Cruikshanks approved these changes

2024-08-30 09:19 UTC, merged