Only include the required information in the metadata field
DEFRA/water-abstraction-system pull request #1299
Opened 2024-08-30 14:44 UTC by robertparkinson

https://eaflood.atlassian.net/browse/WATER-4543

As part of the work to replace the legacy system NALD we need to generate return logs. This PR refactors the metadata field so that it only includes the required information from the points and purposes tables.

2024-08-30 14:56 UTC, Cruikshanks requested changes

2024-08-30 14:56 UTC, Cruikshanks commented on app/services/jobs/return-logs/fetch-return-logs.service.js
> +    .withGraphFetched('returnRequirementPurposes.purpose')
If you only need the legacy IDs and descriptions off these, then they should have `modifyGraph()` functions which specify this in the select.

Without it, Objection.js will do `SELECT *` pulling everything off the record, and for which I have a strict 🚫 rule.

2024-08-30 14:56 UTC, Cruikshanks commented on test/services/jobs/return-logs/fetch-return-logs.service.test.js
> +const PurposeModel = require('../../../../app/models/purpose.model.js')
Just need to sort the ordering of these requires, including the existing ones.

2024-08-30 14:56 UTC, Cruikshanks commented on test/services/jobs/return-logs/fetch-return-logs.service.test.js
> +
These records are pre-seeded in the DB.

We should be able to use their helper `select()` functions to pick them, then assign those picked ones to your test return requirement purposes (just as done with `Region.select()`).

You can then use them again to assert the legacy IDs and descriptions are what you expected.

2024-09-02 09:15 UTC, Beckyrose200 commented on app/services/jobs/return-logs/fetch-return-logs.service.js
> + * @param isSummer - are we running summer cycel or all year - boolean
```suggestion
 * @param {boolean} isSummer - are we running summer cycle or all year
```

2024-09-02 09:15 UTC, Beckyrose200 commented on app/services/jobs/return-logs/fetch-return-logs.service.js
> + * @param licenceReference - if provided only do the return log for that licence reference - string
```suggestion
 * @param {string} licenceReference - if provided only do the return log for that licence reference
```

2024-09-03 10:47 UTC, Cruikshanks approved these changes

2024-09-03 10:52 UTC, merged