Set flags for existing return version
DEFRA/water-abstraction-system pull request #1513
Opened 2024-11-25 14:54 UTC by jonathangoulding

https://eaflood.atlassian.net/browse/WATER-4731

When the copying existing requirements and using previous requirements for returns, the quarterly returns and multiple uploads flags should inherit from the existing return versions.

This takes precedence over the previous defaults set  earlier in the journey.

2024-11-25 23:01 UTC, Cruikshanks requested changes
Just checking whether a test has been inadvertently duplicated, plus a NIT.

2024-11-25 23:01 UTC, Cruikshanks commented on app/services/return-versions/setup/existing/generate-from-existing-requirements.service.js
> + * be persisted to the setup session, if the return version has multiple uploads and if the return version is for quarterly returns
Thank you for correcting the return type. But might I suggest ...

```suggestion
 * @returns {Promise<object>} the return version's return requirements transformed into an array of session return
 * requirements ready to be persisted to the setup session, plus whether the return version allows multiple uploads and
 * quarterly returns
```

2024-11-26 09:58 UTC, jonathangoulding commented on test/services/return-versions/setup/existing/generate-from-existing-requirements.service.test.js
> +
Correct. Not sure how that happened.

2024-11-26 10:27 UTC, Cruikshanks approved these changes
<img src="https://media0.giphy.com/media/S5JILphSqWa32KrrPn/giphy.gif"/>

2024-11-26 10:41 UTC, merged