How would you like to edit this return
DEFRA/water-abstraction-system pull request #1570
Opened 2024-12-16 16:40 UTC by Jozzey

https://eaflood.atlassian.net/browse/WATER-4836

Build a page to enable the user to choose how they would like to edit a return.

2025-01-11 23:16 UTC, Cruikshanks requested changes
The main reason I've asked for changes is it is _not quite_ following the pattern we've used in other pages or presenter tests.

I get that it might seem pointless. Why, for example, go to the effort of adding a validator and associated unit test for something so 'simple'?

The reason is the pattern/convention is intended to save us the effort involved in deciding where the line for 'simple' is. Or coming back to something 12 months later and trying to understand why 'x' does it this way, but 'y' doesn't.

For most pages in this journey, there are existing matching or similar pages we can copy and use. They're there, so each time we have to add a journey (IMHO the bulk of a typical digital service), they get easier and quicker because our library of existing pages keeps growing.

Hope this makes sense, and happy to discuss further if needed.

2025-01-11 23:16 UTC, Cruikshanks commented on test/presenters/return-logs/setup/start.presenter.test.js
> +      describe('when the status is not yet "overdue"', () => {
I know 'overdue' is covered by the test above. However, our unit tests can also serve as a form of documentation. So, usually, in the presenter tests, if a property is based on some logic, we try to cover _all_ expected behaviours in the tests, even if the main "correctly presents the data" already covers it.

So, I would add a final scenario to this group to document that the status will be' overdue' when the due date is less than `today()'.

> This applies to all the properties. Just noticed they are only testing behaviour not covered by "correctly presents the data".

2025-01-13 16:08 UTC, Beckyrose200 commented on app/controllers/return-logs-setup.controller.js
> +  return h.view('return-logs/setup/start.njk', { activeNavBar: 'search', ...pageData })
Not a massive issue but to keep it consistent inside the controller maybe the activeNavBar property can go inside the StartService, like how the Received function looks

```suggestion
  return h.view('return-logs/setup/start.njk', { ...pageData })
```

2025-01-13 16:21 UTC, Beckyrose200 requested changes

2025-01-13 16:21 UTC, Beckyrose200 commented on app/controllers/return-logs-setup.controller.js
> +    return h.view('return-logs/setup/start.njk', {
Not a massive issue but to keep it consistent inside the controller maybe the activeNavBar property can go inside the SubmitStartService, like how the submitReceived function looks
```suggestion
    return h.view('return-logs/setup/start.njk', {...pageData})
```

2025-01-13 16:21 UTC, Beckyrose200 commented on app/services/return-logs/setup/start.service.js
> +  return StartPresenter.go(session)
```suggestion
  const formattedData = StartPresenter.go(session)
  
    return {
    pageTitle: 'Abstraction return',
    activeNavBar: 'search',
    ...formattedData
  }
```

2025-01-13 16:21 UTC, Beckyrose200 commented on app/services/return-logs/setup/start.service.js
> + * Orchestrates fetching and presenting the data needed for the `/return-log-edit/{sessionId}/start` page
```suggestion
 * Orchestrates fetching and presenting the data needed for the `/return-logs/setup/{sessionId}/start` page
```

2025-01-13 16:21 UTC, Beckyrose200 commented on app/services/return-logs/setup/submit-start.service.js
> + * Handles the user submission for the `/return-log-edit/{sessionId}/start` page
```suggestion
 * Handles the user submission for the `/return-logs/setup/{sessionId}/start` page
```

2025-01-13 16:21 UTC, Beckyrose200 commented on app/presenters/return-logs/setup/start.presenter.js
> + * Formats the data ready for presenting in the `/return-log-edit/{sessionId}/start` page
```suggestion
 * Formats the data ready for presenting in the `/return-logs/setup/{sessionId}/start` page
```

2025-01-13 16:21 UTC, Beckyrose200 commented on app/validators/return-logs/setup/start.validator.js
> + * Validates data submitted for the `/return-log-edit/{sessionId}/start` page
```suggestion
 * Validates data submitted for the `/return-logs/setup/{sessionId}/start` page
```

2025-01-13 16:21 UTC, Beckyrose200 commented on app/presenters/return-logs/setup/start.presenter.js
> + * Formats the data ready for presenting in the `/return-log-edit/{sessionId}/start` page
```suggestion
 * Formats the data ready for presenting in the `/return-logs/setup/{sessionId}/start` page
```

2025-01-13 16:21 UTC, Beckyrose200 commented on app/services/return-logs/setup/start.service.js
> + * Orchestrates fetching and presenting the data needed for the `/return-log-edit/{sessionId}/start` page
```suggestion
 * Orchestrates fetching and presenting the data needed for the `/return-logs/setup/{sessionId}/start` page
```

2025-01-13 16:21 UTC, Beckyrose200 commented on app/services/return-logs/setup/submit-start.service.js
> + * Handles the user submission for the `/return-log-edit/{sessionId}/start` page
```suggestion
 * Handles the user submission for the `/return-logs/setup/{sessionId}/start` page
```

2025-01-13 16:54 UTC, Beckyrose200 commented on app/views/return-logs/setup/start.njk
> +      name: "whatToDo",
Maybe name this something like 'journey'

2025-01-13 16:56 UTC, Beckyrose200 commented on app/views/return-logs/setup/start.njk
> +          value: 'nilReturn',
Value should be in kebab case

2025-01-13 16:57 UTC, Beckyrose200 commented on app/presenters/return-logs/setup/start.presenter.js
> +    returnLogId,
Dont need to return returnLogId directly (might need to be in the backlink though)

2025-01-13 16:57 UTC, Beckyrose200 commented on app/presenters/return-logs/setup/start.presenter.js
> +    pageTitle: 'Abstraction return',
Page title can be returned from the service instead of the presenter

2025-01-13 16:59 UTC, Beckyrose200 commented on app/services/return-logs/setup/submit-start.service.js
> + * @param {string} sessionId - The UUID for setup bill run session record
```suggestion
 * @param {string} sessionId - The UUID of the current session
```

2025-01-14 11:28 UTC, Jozzey commented on app/services/return-logs/setup/start.service.js
> +  return StartPresenter.go(session)
Done, but as discussed on the team call this morning, the `pageTitle` should now go in the presenter.

2025-01-14 11:40 UTC, Jozzey commented on app/presenters/return-logs/setup/start.presenter.js
> +    pageTitle: 'Abstraction return',
Following the team discussion this morning, our new standard is to have the `pageTitle` in the presenter.

2025-01-14 16:44 UTC, Jozzey commented on app/presenters/return-logs/setup/start.presenter.js
> +    returnLogId,
I've removed it as it wasn't needed. It was left over from when the page was being built to edit a return log.

2025-01-15 08:57 UTC, Jozzey commented on app/presenters/return-logs/setup/start.presenter.js
> +    abstractionPeriod: `From ${formatAbstractionPeriod(
Spoke with Alan about this after finding that it is linked to from the licence review and charge element review screens. He then told me that we shouldn't be adding a dynamic backlink here as it breaks our pattern, it can stay as it is hardcoded in the view with a dynamic licenceId.

2025-01-15 11:47 UTC, Cruikshanks approved these changes

2025-01-15 12:52 UTC, Beckyrose200 reviewed
Just small comments :)

2025-01-15 12:52 UTC, Beckyrose200 commented on app/presenters/return-logs/setup/start.presenter.js
> + * @returns {object} page data needed for the `/return-log-edit/{sessionId}/start` page
```suggestion
 * @returns {object} page data needed for the `/return-logs/setup/{sessionId}/start` page
```

2025-01-15 12:52 UTC, Beckyrose200 commented on app/views/return-logs/setup/start.njk
> +
```suggestion
```

2025-01-15 12:52 UTC, Beckyrose200 commented on app/views/return-logs/setup/start.njk
> +      {# Bill run meta-data #}
```suggestion
      {# Return meta-data #}
```

2025-01-15 12:52 UTC, Beckyrose200 commented on test/controllers/return-logs-setup.controller.test.js
> +const SubmitStartService = require('../../app/services/return-logs/setup/submit-start.service.js')
Need to switch this with line 21

2025-01-15 13:00 UTC, Jozzey commented on app/views/return-logs/setup/start.njk
> +
That space is there intentionally. It's our convention to put a space between our macro and the govuk ones. There are examples in other views like `app/views/bill-runs/errored.njk`

2025-01-15 13:11 UTC, Beckyrose200 approved these changes
<img src="https://media1.giphy.com/media/V80llXf734WzK/giphy.gif"/>

2025-01-15 13:17 UTC, merged