Reliable test data clear down
DEFRA/water-abstraction-system pull request #215
Opened 2023-05-09 13:24 UTC by Jozzey

https://eaflood.atlassian.net/browse/WATER-3982

Using the existing acceptance tests a common issue we face is that we can’t clear down the existing test data. Because of the solution previously implemented, it only focuses on data flagged as `is_test === true`. The problem is when using this data for test purposes you will often create related data that is not flagged as `is_test`. This leads to errors in the existing clear down process that we then have to create a and run manual SQL delete scripts to deal with.

If we’re often having to write SQL delete scripts manually, and these deal with the foreign key constraints that the existing process isn’t handling, it makes sense to us to use them always rather than the existing brittle process.

2023-05-09 16:19 UTC, Jozzey commented
I've had a word with @Cruikshanks about the test coverage on the schema services. As they are just for deleting test data we've agreed that they are not worth spending time on full unit testing since this would involve significant work in creating the new schemas/data in the test DB.

Testing has been added but just at the high level tear-down service and the controller.

2023-05-10 16:11 UTC, Cruikshanks requested changes
Just some minor changes! I can't wait to give it a spin when done 😁

2023-05-10 16:11 UTC, Cruikshanks commented on app/controllers/data/data.controller.js
> +const Boom = require('@hapi/boom')
Tiny thing! We've got [a convention](https://github.com/DEFRA/water-abstraction-team/blob/main/coding_conventions.md#top-of-js-files) that splits external modules from internal ones with a new line.

```suggestion
const Boom = require('@hapi/boom')

```

2023-05-10 16:11 UTC, Cruikshanks commented on app/routes/data.routes.js
> +      description: 'Used to remove the integration test data from the database',
Potato / potato I know. But we name our UI based test repos 'acceptance tests'. So, that's the name I would use here as well.

 ```suggestion
      description: 'Used to remove the acceptance test data from the database',
```

2023-05-10 16:11 UTC, Cruikshanks commented on test/controllers/data/data.controller.test.js
> +    describe('when a request is valid', () => {
Perhaps ...

```suggestion
    describe('when the request succeeds', () => {
```

2023-05-11 09:45 UTC, Jozzey commented on app/plugins/router.plugin.js
> +  ...RootRoutes
I did wonder why they were in that order. I'll put it back to how it was.

2023-05-11 13:05 UTC, Cruikshanks approved these changes

2023-05-11 13:18 UTC, merged