New billing batch record for SROC supplementary bill run
DEFRA/water-abstraction-system pull request #37
Opened 2022-11-25 16:46 UTC by Jozzey

https://eaflood.atlassian.net/browse/WATER-3830

 We are starting to create the initial records needed in the SROC Supplementary process.

The first is the billing_batch record. Users can view the status of a bill run on the bill runs page. We need this record to support this, plus link/record other values, for example, the charge module’s Bill run ID.

2022-12-08 18:20 UTC, Jozzey commented
I've created a billing-batch test helper but ended up not using it as the billing batch service creates a billing batch so didn't need the helper to do it for me.

I've left the helper in for the time being in case we need it later on, but let me know if you'd like it removed.

2022-12-08 23:08 UTC, Cruikshanks requested changes
Just a real minor change. Over than that, this is bang on the money!

2022-12-08 23:08 UTC, Cruikshanks commented on app/models/region.model.js
> +      billing_batches: {
Just a minor tweak. We can use camelcase for the names of the relationships and that will follow what we've already done in the `LicenceModel`.

```suggestion
      billingBatches: {
```

2022-12-09 09:24 UTC, Cruikshanks approved these changes

2022-12-09 09:53 UTC, merged