Add missing information to `/health/info` page
DEFRA/water-abstraction-system pull request #376
Opened 2023-08-24 15:28 UTC by Jozzey

https://eaflood.atlassian.net/browse/WATER-4099

Finish off the work previously started on the `/health/info` page. The data that is missing that needs to be added in this PR is:
- Confirm Redis is running
- Display the latest results for the import app

2023-09-04 21:57 UTC, Cruikshanks requested changes
We also just need to rename the fetch service (`app/services/health/fetchImportJobs.service.js`). We use kebab case for file names and this doesn't match our convention

2023-09-04 21:57 UTC, Cruikshanks commented on app/services/health/fetchImportJobs.service.js
> + * Calcualtes the current date minus the number of days passed to it
```suggestion
 * Calculates the current date minus the number of days passed to it
```

2023-09-05 09:29 UTC, Cruikshanks approved these changes

2023-09-05 09:42 UTC, merged

2023-09-08 13:07 UTC, Jozzey commented
PR linked to this issue https://github.com/DEFRA/water-abstraction-team/issues/54