Add generic http request module
DEFRA/water-abstraction-system pull request #53
Opened 2022-12-13 17:54 UTC by Cruikshanks

https://eaflood.atlassian.net/browse/WATER-3833

Our `/service-status` page makes `GET` requests to the other services in order to check if they are 'alive'. We now need to start making requests to other external services, for example, the Charging Module API and AWS Cognito (to authenticate with the CHA API).

There are options we want to pass to [got](https://github.com/sindresorhus/got) all the time. Plus we want a standard way of handling the response. **got**, by default, will throw an error for anything other than a `2xx` or `3xx` response. But we normally want the response, including the status code and body as it will determine what we do next.

So, it's time to add a generic HTTP request module to centralise and standardise these things.

2022-12-15 15:22 UTC, Jozzey commented on test/lib/request.lib.test.js
> +            .reply(200, { data: 'hello world' })
```suggestion
            .reply(200, { data: 'delayed hello world' })
```
With the data the same for both the delayed and rapid replies, if the delayed reply wasn't getting timed out the test would still pass

2022-12-15 16:08 UTC, Jozzey submitted a review, later dismissed
<img src="https://media3.giphy.com/media/26njPmXyeB1kCAauk/giphy.gif"/>

2022-12-15 16:35 UTC, StuAA78 requested changes
Just a couple of tiny tweaks that might improve readability but I won't argue over it if you think it's fine as it is 😄

2022-12-15 16:35 UTC, StuAA78 commented on app/lib/request.lib.js
> +    }),
I don't know if using the ternary would be a slightly clearer way of doing this?

```suggestion
    // This uses the ternary operator to give either an `agent` object or an empty object, and the spread operator to
    // bring the result back into the top level of the `defaultOptions` object.
    ...(requestConfig.httpProxy
      ? {
          agent: {
            https: new HttpsProxyAgent({ proxy: requestConfig.httpProxy })
          }
        }
      : {}),
```

2022-12-15 16:35 UTC, StuAA78 commented on app/lib/request.lib.js
> +  return Object.assign(defaultOptions, additionalOptions)
Would this be a slightly simpler way of doing it maybe?
```suggestion
  return { ...defaultOptions, ...additionalOptions }
```

2022-12-15 17:32 UTC, Jozzey approved these changes
<img src="https://media0.giphy.com/media/v9mNF825DPHHDN0i2L/giphy.gif"/>

2022-12-16 10:05 UTC, StuAA78 approved these changes

2022-12-16 10:14 UTC, merged