Create `fetch-returns-for-licence` service
DEFRA/water-abstraction-system pull request #547
Opened 2023-11-23 14:44 UTC by Jozzey

https://eaflood.atlassian.net/browse/WATER-4188

As part of the work we have been doing, we've been hacking away at a branch in a mob to build the two-part-tariff service. As a result of this, we have some refactoring to do to tidy up the work we have done in our mob. We are keeping track of the refactoring to do in this issue https://github.com/DEFRA/water-abstraction-team/issues/105.

This PR will extract the `fetch-returns-for-licence` service out of our hacky branch https://github.com/DEFRA/water-abstraction-system/pull/458 and into its own PR along with the unit tests.

2023-11-23 22:07 UTC, Cruikshanks requested changes
I think we could do with one more test. But happy to chat about it.

2023-11-23 22:07 UTC, Cruikshanks commented on test/services/bill-runs/two-part-tariff/fetch-returns-for-licence.service.test.js
This is great! But you have done such a good job covering the possible scenarios I think it makes clear there is one missing; when there are no returns with a matching licence ref.

What do you think? Should we add one more test to confirm the results are empty?

2023-11-24 09:38 UTC, Jozzey commented on test/services/bill-runs/two-part-tariff/fetch-returns-for-licence.service.test.js
You're right, totally overlooked that one. I'll pop one in.

2023-11-24 16:18 UTC, Cruikshanks approved these changes

2023-11-24 17:21 UTC, merged