Create `water` schema views
DEFRA/water-abstraction-system pull request #551
Opened 2023-11-27 16:40 UTC by Jozzey

https://eaflood.atlassian.net/browse/WATER-4188

As part of the work we have been doing on two-part tariff we are going to be creating all our new tables in a single schema `public`.

We have also decided that when there is a legacy table that we are still going to need for SROC. We are going to create a View of that table in the `public` schema and correct any issues with naming conventions, unused fields etc in the view. The first of these views that represents the old `returns` tables have been created in https://github.com/DEFRA/water-abstraction-system/pull/531

In this PR we will build the migration scripts to create the Views we need for SROC in the `water` schema.

2023-11-28 17:18 UTC, Cruikshanks requested changes
Think there are 1 couple of corrections in here, some suggestions for alternate names.

The key change is dropping the convention of prefixing boolean fields with `is_`, especially as going through this, I have seen they haven't followed the convention of applying it consistently.

2023-11-28 17:18 UTC, Cruikshanks commented on db/migrations/public/20231127212015_create-charge-references-view.js
> +        'is_section_130_agreement_enabled',
Same as previous comment

```suggestion
        'is_section_127_agreement_enabled AS section_127_agreement',
        'scheme',
        'is_restricted_source AS restricted_source',
        'water_model',
        'volume',
        'billing_charge_category_id AS charge_category_id',
        'additional_charges',
        'adjustments',
        'is_section_126_agreement_enabled AS section_126_agreement',
        'is_section_130_agreement_enabled AS section_130_agreement',

```

2023-11-28 17:18 UTC, Cruikshanks commented on db/migrations/public/20231127214320_create-charge-versions-view.js
> +        'billed_upto_date',
Upto isn't a word so we can correct this in the view.

```suggestion
        'billed_upto_date AS billed_up_to_date',

```

2023-11-28 17:18 UTC, Cruikshanks commented on db/migrations/public/20231127222209_create-licences-view.js
> +        'is_water_undertaker',
Same as previous comment

```suggestion
        'is_water_undertaker AS water_undertaker',

```

2023-11-28 17:18 UTC, Cruikshanks commented on db/migrations/public/20231127222209_create-licences-view.js
> +        'include_in_sroc_supplementary_billing',
Not sure this suggestion is necessarily better. But can't afford to miss the opportunity to make these more usable in our code! How about

```suggestion
        'include_in_supplementary_billing AS include_in_presroc_billing',
        'include_in_sroc_supplementary_billing AS include_in_sroc_billing',

```

2023-11-28 17:18 UTC, Cruikshanks commented on db/migrations/public/20231127222742_create-purposes-view.js
> +        'is_two_part_tariff',
Same as previous comment

```suggestion
        'is_two_part_tariff AS two_part_tariff',

```

2023-11-28 17:18 UTC, Cruikshanks commented on db/migrations/public/20231127224323_create-transactions-view.js
> +        'is_water_undertaker',
Same comment as previous

```suggestion
        'is_credit AS credit',
        'charge_type',
        'authorised_quantity',
        'billable_quantity',
        'authorised_days',
        'billable_days',
        'status',
        'description',
        'external_id',
        'volume',
        'section_126_factor',
        'section_127_agreement',
        'section_130_agreement',
        'is_de_minimis AS deminimis',
        'is_new_licence AS new_licence',
        'legacy_id',
        'metadata',
        'source_transaction_id',
        'calc_source_factor',
        'calc_season_factor',
        'calc_loss_factor',
        'calc_suc_factor',
        'calc_s_126_factor',
        'calc_s_127_factor',
        'calc_eiuc_factor',
        'calc_eiuc_source_factor',
        'is_credited_back AS credited_back',
        'is_two_part_second_part_charge AS second_part_charge',
        'scheme',
        'aggregate_factor',
        'adjustment_factor',
        'charge_category_code',
        'charge_category_description',
        'is_supported_source AS supported_source',
        'supported_source_name',
        'is_water_company_charge AS water_company_charge',
        'is_winter_only AS winter_only',
        'is_water_undertaker AS water_undertaker',

```

2023-11-28 17:18 UTC, Cruikshanks commented on db/migrations/public/20231127230416_create-workflows-view.js
> +        'date_deleted',
What do you think about making this consistent with the other fields?

```suggestion
        'date_deleted AS deleted_at',

```

2023-11-29 09:32 UTC, Jozzey commented on db/migrations/public/20231127193216_create-bills-view.js
> +        'is_flagged_for_rebilling',
💯

2023-11-30 11:39 UTC, Cruikshanks approved these changes

2023-11-30 14:42 UTC, merged