Create models, migrations, helpers and unit test for new tables
DEFRA/water-abstraction-system pull request #552
Opened 2023-11-27 16:51 UTC by Beckyrose200

https://eaflood.atlassian.net/browse/WATER-4188

This PR is focusing on creating our 3 new tables for the 2pt matching. These are `review_charge_element_results`, `review_return_results` and `review_results`. This PR includes the migrations, models, helpers and unit tests.

2023-11-27 17:03 UTC, Beckyrose200 commented
* Need to check the purposes column on the `review_return_results` table helper

2023-11-28 15:34 UTC, Cruikshanks requested changes
Few things I think we need to update. The key thing is revisiting the unit tests, either to add some additional ones or switch the pattern being used.

I hope it makes sense.

2023-11-28 15:34 UTC, Cruikshanks commented on test/models/review-charge-element-result.model.test.js
The `ReviewChargeElementResultModel` has a relationship to `ReviewResult` which isn't covered here. It's something we normally add and I think we should continue to do so.

2023-11-28 15:34 UTC, Cruikshanks commented on test/models/review-result.model.test.js
> +    })
If you look at tests for other models we have 2 test patterns we follow; one for `BelongsToOneRelation` and another for `HasManyRelation`.

The key difference is whether we create 1 or multiple test records, and then confirm if we get a single object or array of them back.

This test is the pattern for `BelongsToOneRelation` but the relationship is actually a `HasManyRelation`.

If it helps `test/models/crm-v2/billing-account.model.test.js` has an example of both types that doesn't get too mad!

2023-11-28 15:34 UTC, Cruikshanks commented on test/models/review-result.model.test.js
> +  })
The previous comment applies here as well.

2023-11-28 15:34 UTC, Cruikshanks commented on test/models/review-return-result.model.test.js
The `ReviewReturnResultModel` has a relationship to `ReviewResult` which isn't covered here. It's something we normally add and I think we should continue to do so.

2023-11-28 15:34 UTC, Cruikshanks commented on test/support/helpers/review-charge-element-result.helper.js
> + * - chargeDatesOverlap - false
```suggestion
 * - `id` - [random UUID]
 * - `chargeElementId` - [random UUID]
 * - `allocated` - 0
 * - `aggregate` - 1
 * - `chargeDatesOverlap` - false
```

2023-11-28 15:34 UTC, Cruikshanks commented on test/support/helpers/review-charge-element-result.helper.js
> + * - updatedAt - new Date()
The `created_at` and `updated_at` get automatically populated when the record is created. So, we shouldn't need to default them.

2023-11-28 15:34 UTC, Cruikshanks commented on test/support/helpers/review-result.helper.js
> + * - chargeVersionChangeReason - 'Strategic review of charges (SRoC)'
```suggestion
 * - `chargePeriodStartDate` - 2022-04-01
 * - `chargePeriodEndDate` - 2022-06-05
 * - `chargeVersionChangeReason` - Strategic review of charges (SRoC)
```

2023-11-28 15:34 UTC, Cruikshanks commented on test/support/helpers/review-result.helper.js
> + * - updatedAt - new Date()
The `created_at` and `updated_at` get automatically populated when the record is created. So, we shouldn't need to default them.

2023-11-28 15:34 UTC, Cruikshanks commented on test/support/helpers/review-return-result.helper.js
> + * - abstractionOutsidePeriod - false
```suggestion
 * - `startDate` - 2022-04-01
 * - `endDate` - 2022-05-06
 * - `dueDate` - 2022-06-03
 * - `receivedDate` - 2022-06-03
 * - `status` - completed
 * - `underQuery` - false
 * - `nilReturn` - false
 * - `description` - Lands at Mosshayne Farm, Exeter & Broadclyst
 * - `purposes` - {}
 * - `quantity` - 0
 * - `allocated` - 0
 * - `abstractionOutsidePeriod` - false
```

2023-11-28 15:34 UTC, Cruikshanks commented on test/support/helpers/review-return-result.helper.js
> + *
The `created_at` and `updated_at` get automatically populated when the record is created. So, we shouldn't need to default them.

2023-12-04 13:17 UTC, Cruikshanks commented on test/models/review-result.model.test.js
> +    describe('when linking to review charge element result', () => {
```suggestion
    describe('when linking to review charge element results', () => {
```

2023-12-04 13:40 UTC, Cruikshanks commented on test/models/review-result.model.test.js
> +        expect(result[1].reviewChargeElementResults).to.include(testReviewChargeElementResult)
I think something has gotten last in translation. This is not the pattern we use in our other model unit tests. This is what I would expect to see

```suggestion
        const result = await ReviewResultModel.query()
          .findById(testRecord.id)
          .withGraphFetched('reviewChargeElementResults')

        expect(result).to.be.instanceOf(ReviewResultModel)
        expect(result.id).to.equal(testRecord.id)

        expect(result.reviewChargeElementResults).to.be.an.array()
        expect(result.reviewChargeElementResults[0]).to.be.an.instanceOf(ReviewChargeElementResultModel)
        expect(result.reviewChargeElementResults).to.include(testReviewChargeElementResults[0])
        expect(result.reviewChargeElementResults).to.include(testReviewChargeElementResults[1])
```

2023-12-04 13:40 UTC, Cruikshanks commented on test/models/review-result.model.test.js
> +    describe('when linking to review return result', () => {
```suggestion
    describe('when linking to review return results', () => {
```

2023-12-04 13:40 UTC, Cruikshanks commented on test/models/review-result.model.test.js
> +      it('can eager load the ', async () => {
```suggestion
      it('can eager load the review return results', async () => {
```

2023-12-04 13:42 UTC, Cruikshanks commented on test/models/review-result.model.test.js
> +        expect(result[1].reviewReturnResults).to.include(testReviewReturnResult)
Same as previous comment. This is the patten I was expecting to see

```suggestion
        const result = await ReviewResultModel.query()
          .findById(testRecord.id)
          .withGraphFetched('reviewReturnResults')

        expect(result).to.be.instanceOf(ReviewResultModel)
        expect(result.id).to.equal(testRecord.id)

        expect(result.reviewReturnResults).to.be.an.array()
        expect(result.reviewReturnResults[0]).to.be.an.instanceOf(ReviewReturnResultModel)
        expect(result.reviewReturnResults).to.include(testReviewReturnResults[0])
        expect(result.reviewReturnResults).to.include(testReviewReturnResults[1])
```

2023-12-05 10:20 UTC, Cruikshanks requested changes
Minor, _minor_ tweak to the test descriptions 😁

2023-12-05 10:20 UTC, Cruikshanks commented on test/models/review-result.model.test.js
> +    describe('when linking to review return results', () => {
```suggestion
    describe('when linking to review return result', () => {
```

2023-12-05 10:20 UTC, Cruikshanks commented on test/models/review-result.model.test.js
> +    describe('when linking to review charge element results', () => {
```suggestion
    describe('when linking to review charge element result', () => {
```

2023-12-05 10:48 UTC, Cruikshanks approved these changes
<img src="https://media4.giphy.com/media/laUY2MuoktHPy/giphy.gif"/>

2023-12-05 13:50 UTC, merged