feat(app): WATER-4267 Added setup page
DEFRA/water-abstraction-system pull request #737
Opened 2024-02-14 19:23 UTC by Demwunz

Added setup page for return requirements journey. Step 3 of 7.

2024-02-15 14:20 UTC, robertparkinson requested changes

2024-02-16 09:30 UTC, Demwunz commented on app/services/return-requirements/setup.service.js
> + * Orchestrates fetching and presenting the data for `/return-requirements/{sessionId}/reason` page
good spot, amended

2024-02-16 09:30 UTC, Demwunz commented on app/services/return-requirements/submit-setup.service.js
> + * @module SetupService
good spot, amended

2024-02-16 09:45 UTC, robertparkinson approved these changes

2024-02-16 09:57 UTC, merged