Returns required - How do you want to set up page (3 of 7)
DEFRA/water-abstraction-system pull request #758
Opened 2024-02-23 11:45 UTC by Demwunz

This PR adds the correct routing for this ticket.

https://eaflood.atlassian.net/browse/WATER-4267

The page will redirect to different pages based upon user input.

2024-02-26 22:05 UTC, Cruikshanks requested changes
The most minor of NITs!

2024-02-26 22:05 UTC, Cruikshanks commented on test/services/return-requirements/submit-setup.service.test.js
> +  describe('with different setups', () => {
Just a NIT. We like to leave a line between the `describe()` blocks.

```suggestion

  describe('with different setups', () => {
```

2024-02-27 10:09 UTC, Demwunz commented
Merged your suggestion @Cruikshanks ready for a re-review :)

2024-02-27 11:37 UTC, Cruikshanks approved these changes

2024-02-27 11:46 UTC, merged