Update allocation engine to handle overdue returns
DEFRA/water-abstraction-system pull request #759
Opened 2024-02-23 12:10 UTC by Jozzey

https://eaflood.atlassian.net/browse/WATER-4377

Update the match & allocation engine to ‘allocate’ overdue returns.

The complication is the engine is built on matching return submission lines to charge elements by comparing the line’s start and end dates to a charge element’s calculated abstraction dates (amongst a host of other parameters).

So where there is a licence with an overdue return that has been matched to an element. The engine needs to ensure that the customer is charged the authorised amount for that element.

The engine is to be updated so that after all completed returns have had their volumes allocated. If there are any overdue returns, the engine will attempt to match those to a charge element. If matched the engine will then bump the volume allocated to that element up to its authorised volume.

2024-02-26 22:35 UTC, Cruikshanks requested changes
I'll be honest, I didn't work through every single unit test. But this is fantastic.

The smallest of reasons to request a change!

2024-02-26 22:35 UTC, Cruikshanks commented on app/services/bill-runs/two-part-tariff/allocate-returns-to-charge-element.service.js
> + * charge reference, whichever is lower. If any "due" returns are are matched to a charge element, that element will
Just a typo (great explanation BTW)

```suggestion
 * charge reference, whichever is lower. If any "due" returns are matched to a charge element, that element will
```

2024-02-27 09:26 UTC, Jozzey commented on app/services/bill-runs/two-part-tariff/allocate-returns-to-charge-element.service.js
> + * charge reference, whichever is lower. If any "due" returns are are matched to a charge element, that element will
Thanks. I'll sort the typo.

2024-02-27 10:04 UTC, Cruikshanks approved these changes
<img src="https://media4.giphy.com/media/H4oQb972hKDQE4C4Mv/giphy.gif"/>

2024-02-27 11:27 UTC, merged