Select the purpose for the requirements for returns page
DEFRA/water-abstraction-system pull request #774
Opened 2024-02-29 11:41 UTC by rvsiyad

https://eaflood.atlassian.net/browse/WATER-4294

This is PR is focused on adding functionality to page 1 of 11 in the return requirement pages.

The pages were previously setup as part of a separate PR to create the user journey.

2024-03-14 14:20 UTC, Beckyrose200 requested changes
Really good work, just a few comments :)

2024-03-14 14:20 UTC, Beckyrose200 commented on test/presenters/return-requirements/purpose.presenter.test.js
> +      payload = {
Since payload isn't being reused in any tests this could be a const and you can remove the let on line 16

2024-03-14 14:20 UTC, Beckyrose200 commented on test/services/return-requirements/fetch-purposes.service.test.js
> +const LicenceVersionPurposeHelper = require('../../support/helpers/licence-version-purpose.helper.js')
Switch the order of these to be alphabetical

2024-03-14 14:20 UTC, Beckyrose200 commented on test/services/return-requirements/purpose.service.test.js
> +    await DatabaseSupport.clean()
Add a blank line here

2024-03-14 14:20 UTC, Beckyrose200 commented on test/services/return-requirements/purpose.service.test.js
> +          licencePurposes: [
The purpose.service calls two other services, the `FetchPurposesService` which is stubbed and `SelectPurposePresenter` which isn't stubbed. The presenter needs to be stubbed to test this file independently.

2024-03-14 14:20 UTC, Beckyrose200 commented on test/services/return-requirements/purpose.service.test.js
> +const SelectPurposeService = require('../../../app/services/return-requirements/purpose.service.js')
The module exported on` purpose.service.js` file is called PurposeService but here its is called SelectPurposeService. I would try and keep the naming consistent.

2024-03-14 14:20 UTC, Beckyrose200 commented on test/services/return-requirements/submit-purpose.service.test.js
> +    describe('with an invalid payload', () => {
For these tests the `FetchPurposesService` and `PurposePresenter` are not being stubbed

2024-03-14 14:20 UTC, Beckyrose200 commented on test/validators/no-returns-required/purpose.validator.test.js
> +  describe('when invalid data is provided', () => {
Could these tests be fleshed out a bit more to add more validation errors like the user not picking any options?

2024-03-14 15:10 UTC, rvsiyad commented on app/views/return-requirements/purpose.njk
> +        {% set rowIndex = loop.index0 %}
Remove rowIndex and works regardless :)

2024-03-15 11:17 UTC, Beckyrose200 approved these changes
<img src="https://media2.giphy.com/media/73Y6EEJqbyGovenlLE/giphy.gif"/>

2024-03-15 11:18 UTC, merged