Make timestamps consistent at model layer
DEFRA/water-abstraction-system pull request #85
Opened 2023-01-10 22:47 UTC by Cruikshanks

https://github.com/DEFRA/water-abstraction-team/issues/69

We identified that there are inconsistencies in the legacy database, timestamps in the tables being one of them. We don't want these issues to make a mess of our code. So, until we're ready for some full-scale data migration we're going to deal with them in our model layer.

Timestamps being different across tables is the main inconsistency we noted and this change deals with it.

2023-01-11 23:52 UTC, Cruikshanks commented
If it helps, most of the changes are documenting what is going on! 😳 Also, for @StuAA78 benefit the key section you need to read is this

> But that leads us to the second problem; at this level translations are global. So, any reference to `date_created` would get translated to `created_at`, irrespective of the table referenced. If we only had to worry about database to model it would be okay. The problem is to make queries work we need to be able to translate back from our names to the database version. That is impossible where `created_at` might need to become `date_created`, `created`, or `modified`. With no access to the table name for context we cannot make that decision.
>
> This is why we have accepted we can only support translations when dealing with instances of a model for now.

Hopefully that explains why I had to abandon what we discussed and accept the 'middle option' 😬

2023-01-13 10:39 UTC, Jozzey submitted a review, later dismissed
<img src="https://media1.giphy.com/media/4ziAZTys3ZrdZ7Z6Ys/giphy.gif"/>

2023-01-13 11:33 UTC, StuAA78 requested changes
Looks great! Just a couple of comment tweaks as discussed

2023-01-13 11:33 UTC, StuAA78 commented on app/models/legacy-base.model.js
> +   *}
This is really picky but once I saw it I couldn't unsee it! It just needs a space to line up with L84
```suggestion
   * }
```

2023-01-13 11:33 UTC, StuAA78 commented on app/models/legacy-base.model.js
> +   * called if Knex had been used to generate the migrations and build the tables.
As discussed we probably want to distinguish between what we would want to see the column as (ie. `created_at`) and how we want to refer to it in our code (ie. `createdAt`)

2023-01-13 17:03 UTC, Jozzey approved these changes

2023-01-13 17:55 UTC, merged