create returns from abstraction data
DEFRA/water-abstraction-system pull request #913
Opened 2024-04-16 12:41 UTC by robertparkinson

https://eaflood.atlassian.net/browse/WATER-4442

This story covers the creation of return requirements based from the abstraction data that is in the licence

2024-05-13 19:41 UTC, Cruikshanks requested changes
I'm not finished! But my machine is forcing a restart. So, just to avoid loosing the suggestions I've already made completing this review for now. 😬

2024-05-13 19:41 UTC, Cruikshanks commented on app/lib/general.lib.js
> + * @returns {String} a description of the abstraction point
Just missing the param

```suggestion
 * a string that defines the details of the abstraction point.
 *
 * @param {Object} pointDetail - Object containing all the details for the point 
 *
 * @returns {String} a description of the abstraction point
```

2024-05-13 19:41 UTC, Cruikshanks commented on app/services/return-requirements/check.service.js
> +
If we don't need it we should delete it. Assuming this just got overlooked!

```suggestion
```

2024-05-13 19:41 UTC, Cruikshanks commented on app/services/return-requirements/check.service.js
> +// const FetchReturnRequirementsBasedOnAbstractionDataService = require('./fetch-requirements-for-returns-from-abstraction-data.service.js')
```suggestion
```

2024-05-13 19:41 UTC, Cruikshanks commented on app/views/return-requirements/check-your-answers.njk
If you changed something in this file as part of the PR it will explain why it is trying to add it. However, this was renamed as `check.njk` and updated in my big tidy up PR.

If you haven't changed anything in the file you can remove it. Else whatever change you made needs to be made to `check.njk`.

2024-05-13 19:41 UTC, Cruikshanks commented on app/services/return-requirements/fetch-requirements-for-returns-from-abstraction-data.service.js
> +function _calculateReportingCycle (licenceData, licenceVersionPurpose) {
I think the name should be changed to fit in with the step in the journey and the collection function.

```suggestion
function _calculateReportingFrequency (licenceData, licenceVersionPurpose) {
```

2024-05-13 19:41 UTC, Cruikshanks commented on app/services/return-requirements/fetch-requirements-for-returns-from-abstraction-data.service.js
> +  }
I encourage folks to use a [guard clause approach](https://en.wikipedia.org/wiki/Guard_(computer_science)) to `if` statements like this. IMHO they read clearer and ensure you always have a distinct return statement.

```suggestion
  if (licenceVersionPurpose.dailyQuantity <= upperDailyQuantityThreshold) {
    return 'monthly'
  }
  
  return 'weekly'
```

2024-05-13 19:41 UTC, Cruikshanks commented on app/services/return-requirements/fetch-requirements-for-returns-from-abstraction-data.service.js
> +  }
Would also suggest a guard clause style approach here as well.

```suggestion
  if (licenceVersionPurpose.dailyQuantity < minimumDailyQuantityThreshold) {
    return 'none'
  }
  
  if (licenceVersionPurpose.dailyQuantity <= upperDailyQuantityThreshold) {
    return 'monthly'
  }
  
  return 'weekly'
```

2024-05-14 07:45 UTC, Cruikshanks requested changes
A couple more points. But also a question about how the data is being fetched that would be worth answering before I go deeper.

I could also really do with the PR title and description being firmed up. What I read makes it sound like we are _creating_ the requirement you'll see on the `/check` page.

I could be wrong, but what I'm seeing is the things needed to fetch and format the data _in preparation_ of creating the session requirement.

Ping me if you want a chat or clearer guidance!

2024-05-14 07:45 UTC, Cruikshanks commented on app/services/return-requirements/fetch-requirements-for-returns-from-abstraction-data.service.js
I love verbose names! But I reckon in this case we can simplify things a bit. How about `fetch-requirements-from-abstraction-data.service.js`?

2024-05-14 07:45 UTC, Cruikshanks commented on app/services/licences/fetch-licence-summary.service.js
Do we need _everything_ this fetch service provides plus these additional 3 fields? Or is it the case this service provides some stuff we need apart from these 3 fields?

If it's the latter we will normally create a specific fetch service for the use case. We'll then look at what if anything can be refactored as shareable/reusable afterwards.

This might also answer my thoughts on whether we could simplify `fetch-requirements-for-returns-from-abstraction-data.service.js` by moving some of the work into the query.

2024-05-14 08:31 UTC, robertparkinson commented on app/services/licences/fetch-licence-summary.service.js
It would need the `permitLicence`, `licenceRef`, `licenceVersions`,  which are the big bits that are used in the licence summary page. I've added `waterUndertaker` which is not used in the licence summary page. 

I can create a separate fetch service for it. I just thought reusing the existing service would cut down on code duplication

2024-05-14 08:55 UTC, Cruikshanks commented on app/services/licences/fetch-licence-summary.service.js
I'm fine with a bit of duplication. I find that a clearer 'smell' of when something needs refactoring rather than preemptively doing it.

For example, I don't think we're using licence holder or the gauging stations from `FetchLicenceSummaryService`. So, having a dedicated service makes it clearer what we actually need.

2024-06-14 14:47 UTC, Cruikshanks commented
Superseded by https://github.com/DEFRA/water-abstraction-system/pull/1107

2024-06-14 14:47 UTC, closed without merging