Fix validation messages for two-part tariff billable returns page
DEFRA/water-abstraction-system pull request #940
Opened 2024-04-25 09:56 UTC by Beckyrose200

https://eaflood.atlassian.net/browse/WATER-4370

During testing for the above ticket, it was found that a new validation was needed for the custom quantity that a user can enter. This quantity can not be greater than the authorised quantity on the charge element. This PR is to add this validation and to amend the original validation messages to update them as per the design team's request.

2024-04-25 16:19 UTC, Jozzey reviewed
Just a typo, think it got overlooked in the last PR, sorry. Looks OK to me apart from that. Think Alan is also reviewing this so maybe wait and see if he spots anything.

2024-04-25 16:47 UTC, Cruikshanks requested changes
I also spotted just a typo!

2024-04-26 09:36 UTC, Jozzey approved these changes
<img src="https://media3.giphy.com/media/26gsvAm8UPaczzXz2/giphy.gif"/>

2024-04-26 11:11 UTC, Cruikshanks approved these changes

2024-04-26 11:13 UTC, merged